name: Deploy to Dev

on:
  push:
    branches: [ dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/project:scalestash.io.landing.latest
        
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        timeout: 60s
        command_timeout: 300s
        script: |
          # Login to DockerHub for private repo access
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          
          # Pull latest image
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/project:scalestash.io.landing.latest
          
          # Stop and remove existing container
          docker stop scalestash-landing || true
          docker rm scalestash-landing || true
          
          # Run new container
          docker run -d \
            --name scalestash-landing \
            -p 3000:3000 \
            --restart unless-stopped \
            ${{ secrets.DOCKERHUB_USERNAME }}/project:scalestash.io.landing.latest 
          
          docker image prune -f
          docker container prune -f
